env:
  OLLAMA_BASE_URL: "http://r2d2.echobase.network:11434"

image:
  repository: ghcr.io/open-webui/open-webui@sha256:e0d5de16978786b8a7538adf1efcde5258f38faf

ingress:
  hosts: openwebui.echobase.network
  host: openwebui.echobase.network
