env:
  OLLAMA_BASE_URL: "http://r2d2.echobase.network:11434"

image:
  repository: ghcr.io/open-webui/open-webui@sha256:b8a5befbb9a7ee21f478282d9bb3a9559cc14be6568718a7c5e7209399c07956

ingress:
  hosts: openwebui.echobase.network
  host: openwebui.echobase.network
