apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            name: "maul"
    - clusters:
        selector:
          matchLabels:
            name: "vader"
    - clusters:
        selector:
          matchLabels:
            name: "kenobi"
  template:
    metadata:
      name: nginx-{{.name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/kubernetes/ingress-nginx.git
        path: deploy/static/provider/cloud
        targetRevision: ad643baabbbf55d59c60e75330a193545aa8b788 # v1.14.0
        kustomize:
          patches:
            - target:
                kind: Deployment
                name: ingress-nginx-controller
              patch: |-
                - op: add
                  path: /spec/template/spec/containers/0/args/-
                  value: --enable-metrics
          commonAnnotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
            prometheus.io/scheme: "http"
            prometheus.io/path: "/metrics"
      destination:
        server: "{{.server}}"
        namespace: ingress-nginx
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
