apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - base/argo-cd.yaml
  - base/blocky.yaml
  - base/cert-manager.yaml
  - base/cluster-config.yaml
  - base/distribution.yaml
  #- base/forwardproxy.yaml
  - base/graf.yaml
  - base/ingress-nginx.yaml
  #- base/litellm-proxy.yaml
  - base/metallb.yaml
  #- base/opensearch-cluster.yaml
  #- base/opensearch-operator.yaml
  - base/openwebui.yaml
  - base/prom.yaml
  #- base/qdrant.yaml
  #- base/redis.yaml
  - base/sync-argocd-apps.yaml
  - base/testserver.yaml
